{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: lodestar-artifacts-configuration
type: Opaque
stringData:
  GITLAB_API_URL: "{{ .Values.api.gitlab }}"
  ENGAGEMENT_API_URL: "{{ .Values.api.engagement }}"
  DATABASE_SERVICE_NAME: "{{ .Values.db.mongodbServiceName }}"
  MONGODB_USER: "{{ .Values.db.mongodbUser }}"
  MONGODB_PASSWORD: "{{ .Values.db.mongodbPassword }}"
  MONGODB_DATABASE: "{{ .Values.db.mongodbDatabase }}"
  MONGODB_ADMIN_PASSWORD: "{{ .Values.db.mongodbAdminPassword }}"
  GROUP_PARENT_ID: "{{ .Values.config.gitlabGroupId }}"
  GITLAB_TOKEN: "{{ .Values.tokens.gitlab }}"
{{- end }}
